### ISSUE TITLE
[🐛 Bug]: Zabbix 7.0 Alerting Failure and Media Type Test Error

### ISSUE THREAD

**Issue by hieuny613** [keephq/keep#1763]
itle: Zabbix 7.0 Alerting Failure and Media Type Test Error

Description:

I'm experiencing an issue with Zabbix 7.0 where alerts are not being sent as expected. Additionally, when testing the configured media types, the tests fail with an error.
Environment:
Zabbix Version: 7.0
`00:00:00.000 [Debug] [Keep Webhook] keepApiUrl:http://keep.xxxx.com/webhook/alerts/event/zabbix?provider_id=00c677d7dfab4051bf2ef5e735f02ec5
00:00:00.000 [Debug] [Keep Webhook] keepApiKey:34a6af44-b99b-4185-b1fb-a8101c63c6e9
00:00:00.000 [Debug] [Keep Webhook] Sending request:{"ALERT.SUBJECT":"{ALERT.SUBJECT}","description":"{TRIGGER.DESCRIPTION}","EVENT.SEVERITY":"{EVENT.SEVERITY}","EVENT.TIME":"{EVENT.TIME}","EVENT.VALUE":"{EVENT.VALUE}","HOST.IP":"{HOST.IP}","HOST.NAME":"{HOST.NAME}","id":"{EVENT.ID}","lastReceived":"{DATE} {TIME}","message":"{ALERT.MESSAGE}","name":"{EVENT.NAME}","service":"{HOST.HOST}","severity":"{TRIGGER.SEVERITY}","status":"{TRIGGER.STATUS}","tags":"{EVENT.TAGSJSON}","triggerId":"{TRIGGER.ID}","ZABBIX.URL":"{$ZABBIX.URL}"}
00:00:00.007 [Debug] [Keep Webhook] Received response: HTTP 202:
00:00:00.008 [Warning] [Keep Webhook] Notification failed : Response code not 200`
![image](https://github.com/user-attachments/assets/07019a3a-e9a7-40a4-9b71-eb2cbd271b3e)

`{"asctime": "2024-08-29 17:08:52,180", "message": "Error processing event", "levelname": "ERROR", "name": "keep.api.tasks.process_event_task", "filename": "process_event_task.py", "otelTraceID": "7bea24be418b7be284212c6563f17bad", "otelSpanID": "71c0a064060f488e", "otelServiceName": "keep-api", "threadName": "AnyIO worker thread", "process": 15, "module": "process_event_task", "exc_info": "Traceback (most recent call last):\n  File \"/venv/lib/python3.11/site-packages/keep/api/tasks/process_event_task.py\", line 449, in process_event\n    event = provider_class.format_alert(event, None)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/keep/providers/base/base_provider.py\", line 313, in format_alert\n    formatted_alert = cls._format_alert(event, provider_instance)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/keep/providers/zabbix_provider/zabbix_provider.py\", line 564, in _format_alert\n    for tag in json.loads(event.pop(\"tags\", \"[]\"))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)", "otelTraceSampled": true, "tenant_id": "keep", "provider_type": "zabbix", "provider_id": "00c677d7dfab4051bf2ef5e735f02ec5", "fingerprint": null, "event_type": "<class 'dict'>", "trace_id": "7bea24be418b7be284212c6563f17bad", "raw_event": null}`

**Comment by shahargl** [comment]
Hey @hieuny613, thanks for opening this ticket. I’ll get to it asap. Will update soon.

**Comment by hieuny613** [comment]
> Hey @hieuny613, thanks for opening this ticket. I’ll get to it asap. Will update soon.

Zabbix 6.4 Alerting Failure, Media Type Test Error and No Actions Triggered
`{"asctime": "2024-08-30 04:20:18,218", "message": "Error processing event", "levelname": "ERROR", "name": "keep.api.tasks.process_event_task", "filename": "process_event_task.py", "otelTraceID": "d814e254865d101959ca4ff13c898241", "otelSpanID": "d6861648a325bb33", "otelServiceName": "keep-api", "threadName": "AnyIO worker thread", "process": 17, "module": "process_event_task", "exc_info": "Traceback (most recent call last):\n  File \"/venv/lib/python3.11/site-packages/keep/api/tasks/process_event_task.py\", line 449, in process_event\n    event = provider_class.format_alert(event, None)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/keep/providers/base/base_provider.py\", line 313, in format_alert\n    formatted_alert = cls._format_alert(event, provider_instance)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/keep/providers/zabbix_provider/zabbix_provider.py\", line 564, in _format_alert\n    for tag in json.loads(event.pop(\"tags\", \"[]\"))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/decoder.py\", line 353, in raw_decode\n    obj, end = self.scan_once(s, idx)\n               ^^^^^^^^^^^^^^^^^^^^^^\njson.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)", "otelTraceSampled": true, "tenant_id": "keep", "provider_type": "zabbix", "provider_id": "87f47b053c9b4ee59096d6a3dc6683dc", "fingerprint": null, "event_type": "<class 'dict'>", "trace_id": "d814e254865d101959ca4ff13c898241", "raw_event": null}`

![image](https://github.com/user-attachments/assets/75e83ccb-c2b5-430d-94e5-bed6d1b696bf)
![image](https://github.com/user-attachments/assets/2d851cd5-6b34-48f0-8909-86320678e09f)

**Comment by talboren** [comment]
Thanks for the screenshots @hieuny613 
Will push a fix shortly

**Comment by talboren** [comment]
@hieuny613 I pushed a small fix (kinda, just wrapping up tags extraction with try/catch and logging it because seems like it's not a valid JSON for some reason).
I also fixed the issue with status_code in the media type, can you remove it and install the latest again?

new docker image will be ready in 3-4 minutes.
Let me know if it still fails, I'll do my best to fix it ASAP.

**Comment by hieuny613** [comment]
Zabbix server 6.4

The media type test still encounters an error.
![image](https://github.com/user-attachments/assets/e398efc7-e120-4087-a2a3-e2f37b331dc2)
`{"asctime": "2024-08-30 08:17:52,781", "message": "Failed to extract Zabbix tags", "levelname": "ERROR", "name": "keep.providers.zabbix_provider.zabbix_provider", "filename": "zabbix_provider.py", "otelTraceID": "df0cdc3e9daa4b1786b68133d87278cc", "otelSpanID": "36b8c043ee448a8e", "otelServiceName": "keep-api", "threadName": "AnyIO worker thread", "process": 12, "module": "zabbix_provider", "otelTraceSampled": true, "tags_raw": "{EVENT.TAGSJSON}"}
{"asctime": "2024-08-30 08:17:52,785", "message": "Error processing event", "levelname": "ERROR", "name": "keep.api.tasks.process_event_task", "filename": "process_event_task.py", "otelTraceID": "df0cdc3e9daa4b1786b68133d87278cc", "otelSpanID": "36b8c043ee448a8e", "otelServiceName": "keep-api", "threadName": "AnyIO worker thread", "process": 12, "module": "process_event_task", "exc_info": "Traceback (most recent call last):\n  File \"/venv/lib/python3.11/site-packages/keep/api/tasks/process_event_task.py\", line 449, in process_event\n    event = provider_class.format_alert(event, None)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/keep/providers/base/base_provider.py\", line 313, in format_alert\n    formatted_alert = cls._format_alert(event, provider_instance)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/keep/providers/zabbix_provider/zabbix_provider.py\", line 592, in _format_alert\n    return AlertDto(\n           ^^^^^^^^^\n  File \"pydantic/main.py\", line 341, in pydantic.main.BaseModel.__init__\npydantic.error_wrappers.ValidationError: 2 validation errors for AlertDto\nlastReceived\n  Invalid date format: {DATE} {TIME} (type=value_error)\nurl\n  invalid or missing URL scheme (type=value_error.url.scheme)", "otelTraceSampled": true, "tenant_id": "keep", "provider_type": "zabbix", "provider_id": "8fdcf9d779dc4c488cd0f17af9e988d4", "fingerprint": null, "event_type": "<class 'dict'>", "trace_id": "df0cdc3e9daa4b1786b68133d87278cc", "raw_event": null}
{"asctime": "2024-08-30 08:17:52,786", "message": "Event processed", "levelname": "INFO", "name": "keep.api.tasks.process_event_task", "filename": "process_event_task.py", "otelTraceID": "df0cdc3e9daa4b1786b68133d87278cc", "otelSpanID": "36b8c043ee448a8e", "otelServiceName": "keep-api", "threadName": "AnyIO worker thread", "process": 12, "module": "process_event_task", "otelTraceSampled": true, "tenant_id": "keep", "provider_type": "zabbix", "provider_id": "8fdcf9d779dc4c488cd0f17af9e988d4", "fingerprint": null, "event_type": "<class 'dict'>", "trace_id": "df0cdc3e9daa4b1786b68133d87278cc", "raw_event": null}`

The alert has been pushed to Keep, but it does not include the host information fields.
When the alert is handled in Zabbix, the alert in Keep changes status.
The issue with pushing alerts has been resolved, but when an alert is repeated after being handled, it is not pushed to Keep.
![image](https://github.com/user-attachments/assets/388c2daa-3442-47ec-b7fc-fefdf9121924)
![image](https://github.com/user-attachments/assets/35b51265-418e-4283-bd88-4c1d081257fb)

**Comment by talboren** [comment]
@hieuny613 regarding first issue: it looks like the problem is related with "Test" methond, which I assume you use. It is not parsing the attributes properly but rather sends them plainly (e.g., {EVENT.TAGSJSON} is send as is instead of being parsed to list of tags). I think it's OK but will try to fix that anyway.

regarding second issue, where media type is still failing - I'm pushing a fix for that.

> The issue with pushing alerts has been resolved, but when an alert is repeated after being handled, it is not pushed to Keep.

Regarding this thing, can you explain further? I'm not sure what's happening here. What do you mean exactly? A video would be perfect.

**Comment by talboren** [comment]
@hieuny613 if you may also add the configuration for the media type in Zabbix that would be perfect. Is it configured to send **ALL** updates to Keep?
I would love to hop on a quick call and try to debug it together, if you're up for it :) https://slack.keephq.dev if you wanna chat more easily
